{{- if .Values.bot.enabled }}
{{- if .Values.bot.ingress.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "freqtrade-testing.fullname" . }}-svc
  labels: {{ include "freqtrade-testing.labels" . | nindent 4 }}
spec:
  type: {{ .Values.bot.service.type | default "ClusterIP" }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector: {{ include "freqtrade-testing.labels" . | nindent 4 }}
---
{{ $nm := include "freqtrade-testing.fullname" . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "freqtrade-testing.fullname" . }}
  labels: {{ include "freqtrade-testing.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.bot.ingress.annotations }}
    {{ toYaml .Values.bot.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.bot.ingress.tls }}
  tls:
  - hosts:
      {{- range .Values.bot.ingress.hosts }}
      - {{ . }}
      {{- end }}
    secretName: {{ .Values.bot.ingress.tlsSecretName }}
  {{- end }}
  rules:
  {{- range .Values.bot.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $nm }}-svc
            port:
              number: 8080
  {{- end }}
{{- end }}

{{- if .Values.bot.pvc.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "freqtrade-testing.fullname" . }}-bot
  labels: {{ include "freqtrade-testing.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.bot.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.bot.pvc.size }}
  {{- if .Values.bot.pvc.storageClass }}
  storageClassName: {{ .Values.bot.pvc.storageClass }}
  {{- end }}
{{- end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "freqtrade-testing.fullname" . }}
  labels: {{ include "freqtrade-testing.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{ include "freqtrade-testing.labels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "freqtrade-testing.labels" . | nindent 8 }}
      {{- if .Values.bot.rollme }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      {{- end }}
    spec:
      containers:
      - name: bot
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
        command:
        - freqtrade
        args:
        - trade
        - --config
        - /freqtrade/config/config.json
        - --strategy
        - {{ .Values.strategyName }}
        - --db-url
        - {{ .Values.bot.dbURL }}
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
        - mountPath: /sql
          name: sql
        - mountPath: /freqtrade/user_data/strategies
          name: strategy
        - mountPath: /freqtrade/config/config.json
          name: configmap
          {{- if .Values.bot.configOverride.enabled}}
          subPath: config-bot.json
          {{- else }}
          subPath: config.json
          {{- end }}
        - mountPath: /freqtrade/user_data/strategies/{{ .Values.strategyName }}.py
          name: configmap
          subPath: {{ .Values.strategyName }}.py
        resources:
          {{- toYaml .Values.bot.resources | nindent 12 }}
      {{- if .Values.bot.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.bot.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.bot.affinity }}
      affinity:
        {{ toYaml .Values.bot.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.bot.tolerations }}
      tolerations:
        {{ toYaml .Values.bot.tolerations | nindent 8 }}
      {{- end }}
      volumes:
      - name: strategy
        {{- if .Values.pvc.strategy.useExistingPVC }}
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.strategy.existingPVCName }}
        {{- else if .Values.pvc.strategy.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "freqtrade-testing.fullname" . }}-strategy
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: sql
        {{- if .Values.bot.pvc.useExistingPVC }}
        persistentVolumeClaim:
          claimName: {{ .Values.bot.pvc.existingPVCName }}
        {{- else if .Values.bot.pvc.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "freqtrade-testing.fullname" . }}-bot
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: configmap
        configMap:
          name: {{ include "freqtrade-testing.fullname" . }}-config
{{- end }}
