{{- if .Values.testing.enabled }}

{{- if or .Values.testing.backtesting.enabled .Values.testing.hyperopt.enabled }}

# Calculate backtesting and hyperopt time ranges
{{- $ba := printf "-%dh" (mul 24 (add .Values.testing.backtesting.days .Values.testing.backtesting.offset )) }}
{{- $bo := printf "-%dh" (mul 24 .Values.testing.backtesting.offset ) }}

{{- $ha := printf "-%dh" (mul 24 (add .Values.testing.hyperopt.days .Values.testing.hyperopt.offset )) }}
{{- $ho := printf "-%dh" (mul 24 .Values.testing.hyperopt.offset ) }}

---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-{{ include "freqtrade-testing.fullname" . }}-{{ now | unixEpoch }}
  labels:
    app: job-{{ include "freqtrade-testing.fullname" . }}
spec:
  backoffLimit: 0
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: job-{{ include "freqtrade-testing.fullname" . }}
    spec:
      initContainers:
      {{- if .Values.pvc.sharedData.fixPermissions }}
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chmod 777 /data"]
        volumeMounts:
          - name: shared-data
            mountPath: /data
      {{- end }}
      {{- if .Values.testing.download_data.enabled }}
      - name: download-data
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
        command:
        - freqtrade
        args:
        - download-data
        {{- if .Values.testing.download_data.dl_trades }}
        - --dl-trades
        {{- end }}
        - --pairs
        {{- concat .Values.testing.download_data.pair_whitelist .Values.config.exchange.pair_whitelist | uniq | toYaml | nindent 8 }}
        - --days
        - "{{ .Values.testing.download_data.days }}"
        - --timeframes
        {{- ( concat ( list .Values.config.timeframe ) .Values.testing.download_data.timeframes ) | uniq | toYaml | nindent 8 }}
        - --datadir
        - /data/{{ .Values.config.exchange.name | default "binance" }}
        - --config
        - /freqtrade/config/config.json
        {{- with .Values.testing.download_data.extraArgs }}
        {{ . | toYaml | nindent 8 }}
        {{- end }}
        resources:
          {{- toYaml .Values.testing.download_data.resources | nindent 12 }}
        volumeMounts:
        - mountPath: /data
          name: shared-data
          subPath: data
        - mountPath: /freqtrade/config/config.json
          name: configmap
          subPath: config.json
      {{- end }}

      {{- if and .Values.testing.backtesting.enabled (not .Values.testing.hyperopt.enabled) }}
      containers:
      {{- end }}

      {{- if and (not .Values.testing.backtesting.enabled) .Values.testing.hyperopt.enabled }}
      containers:
      {{- end }}

      {{- if .Values.testing.hyperopt.enabled }}
      - name: hyperopt
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
        command:
        - freqtrade
        args:
        - hyperopt
        - --config
        - /freqtrade/config/config.json
        - --datadir
        - /data/{{ .Values.config.exchange.name | default "binance" }}
        - --hyperopt-loss
        - {{ .Values.testing.hyperopt.hyperoptStrategy }}
        - --spaces
        {{ .Values.testing.hyperopt.spaces | toYaml | nindent 8 }}
        - --strategy
        - {{ .Values.strategyName }}{{ .Values.config.timeframe }}
        {{- if .Values.testing.hyperopt.fee }}
        - --fee
        - {{ .Values.testing.hyperopt.fee | quote }}
        {{- end }}
        - -e
        - "{{ .Values.testing.hyperopt.tries }}"
        {{- if .Values.testing.hyperopt.days }}
        - --timerange
        - {{ now | mustDateModify $ha | date "20060102-" }}{{ now | mustDateModify $ho | date "20060102" }}
        {{- end }}
        {{- with .Values.testing.hyperopt.extraArgs }}
        {{ . | toYaml | nindent 8 }}
        {{- end }}
        volumeMounts:
        - mountPath: /data
          name: shared-data
          subPath: data
        - mountPath: /freqtrade/user_data/strategies
          name: shared-data
          subPath: strategies
        - mountPath: /freqtrade/config/config.json
          name: configmap
          subPath: config.json
        - mountPath: /freqtrade/user_data/strategies/{{ .Values.strategyName }}{{ .Values.config.timeframe }}.py
          name: configmap
          subPath: {{ .Values.strategyName }}{{ .Values.config.timeframe }}.py
        resources:
          {{- toYaml .Values.testing.hyperopt.resources | nindent 12 }}
      {{- end }}

      {{- if and  .Values.testing.backtesting.enabled .Values.testing.hyperopt.enabled }}
      containers:
      {{- end }}

      {{- if .Values.testing.backtesting.enabled }}
      - name: backtesting
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
        command:
        - freqtrade
        args:
        - backtesting
        - --config
        - /freqtrade/config/config.json
        - --datadir
        - /data/{{ .Values.config.exchange.name | default "binance" }}
        - --breakdown
        - {{ .Values.testing.backtesting.breakdown }}
        - --strategy-list
        - {{ .Values.strategyName }}{{ .Values.config.timeframe }}
        {{- if .Values.testing.backtesting.days }}
        - --timerange
        - {{ now | mustDateModify $ba | date "20060102-" }}{{ now | mustDateModify $bo | date "20060102" }}
        {{- end }}
        {{- if .Values.testing.backtesting.fee }}
        - --fee
        - {{ .Values.testing.backtesting.fee | quote }}
        {{- end }}
        {{- with .Values.testing.backtesting.extraArgs }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
        volumeMounts:
        - mountPath: /data
          name: shared-data
          subPath: data
        - mountPath: /freqtrade/user_data/strategies
          name: shared-data
          subPath: strategies
        - mountPath: /freqtrade/user_data/backtest_results
          name: shared-data
          subPath: backtest_results
        - mountPath: /freqtrade/config/config.json
          name: configmap
          subPath: config.json
        - mountPath: /freqtrade/user_data/strategies/{{ .Values.strategyName }}{{ .Values.config.timeframe }}.py
          name: configmap
          subPath: {{ .Values.strategyName }}{{ .Values.config.timeframe }}.py
        resources:
          {{- toYaml .Values.testing.backtesting.resources | nindent 12 }}
      restartPolicy: Never
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      volumes:
      - name: shared-data
        {{- if .Values.pvc.sharedData.useExistingPVC }}
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.sharedData.existingPVCName }}
        {{- else if .Values.pvc.sharedData.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "freqtrade-testing.fullname" . }}-shared-data
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: configmap
        configMap:
          name: {{ include "freqtrade-testing.fullname" . }}-config
{{- end }}

{{- end }}
{{- end }}


